create extension if not exists vector;

create table if not exists public.pyq_papers (
  id text primary key,
  course_code text not null,
  course_name text,
  year integer,
  exam_session text not null,
  title text not null,
  drive_url text not null,
  source_folder_id text,
  source_file_name text,
  processing_status text not null default 'pending' check (processing_status in ('pending', 'processing', 'completed', 'failed', 'skipped')),
  processing_error text,
  processed_at timestamptz,
  content_hash text,
  page_count integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pyq_questions (
  id bigint generated by default as identity primary key,
  paper_id text not null references public.pyq_papers(id) on delete cascade,
  question_number text not null,
  question_text text not null,
  normalized_question text not null,
  section text,
  marks numeric,
  unit text,
  source_page integer not null check (source_page > 0),
  extraction_method text not null default 'text' check (extraction_method in ('text', 'vision')),
  extraction_confidence numeric check (extraction_confidence is null or (extraction_confidence >= 0 and extraction_confidence <= 1)),
  embedding vector(768),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pyq_question_groups (
  id bigint generated by default as identity primary key,
  course_code text not null,
  representative_title text not null,
  representative_description text,
  frequency integer not null default 0 check (frequency >= 0),
  confidence numeric check (confidence is null or (confidence >= 0 and confidence <= 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pyq_question_group_members (
  group_id bigint not null references public.pyq_question_groups(id) on delete cascade,
  question_id bigint not null references public.pyq_questions(id) on delete cascade,
  similarity_score numeric not null check (similarity_score >= 0 and similarity_score <= 1),
  primary key (group_id, question_id)
);

create table if not exists public.pyq_course_analysis_cache (
  course_code text primary key,
  year_from integer,
  year_to integer,
  analysis jsonb not null default '{}'::jsonb,
  processed_paper_count integer not null default 0,
  generated_at timestamptz not null default now(),
  invalidated_at timestamptz
);

create index if not exists pyq_papers_course_code_idx on public.pyq_papers(course_code);
create index if not exists pyq_papers_processing_status_idx on public.pyq_papers(processing_status);
create index if not exists pyq_questions_paper_id_idx on public.pyq_questions(paper_id);
create index if not exists pyq_questions_course_lookup_idx on public.pyq_questions(paper_id, source_page);
create index if not exists pyq_groups_course_code_idx on public.pyq_question_groups(course_code);
create index if not exists pyq_group_members_question_idx on public.pyq_question_group_members(question_id);

create or replace function public.set_pyq_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists pyq_papers_set_updated_at on public.pyq_papers;
create trigger pyq_papers_set_updated_at
before update on public.pyq_papers
for each row execute function public.set_pyq_updated_at();

drop trigger if exists pyq_questions_set_updated_at on public.pyq_questions;
create trigger pyq_questions_set_updated_at
before update on public.pyq_questions
for each row execute function public.set_pyq_updated_at();

drop trigger if exists pyq_question_groups_set_updated_at on public.pyq_question_groups;
create trigger pyq_question_groups_set_updated_at
before update on public.pyq_question_groups
for each row execute function public.set_pyq_updated_at();

alter table public.pyq_papers enable row level security;
alter table public.pyq_questions enable row level security;
alter table public.pyq_question_groups enable row level security;
alter table public.pyq_question_group_members enable row level security;
alter table public.pyq_course_analysis_cache enable row level security;

drop policy if exists pyq_papers_public_read on public.pyq_papers;
create policy pyq_papers_public_read on public.pyq_papers for select using (true);

drop policy if exists pyq_questions_public_read on public.pyq_questions;
create policy pyq_questions_public_read on public.pyq_questions for select using (true);

drop policy if exists pyq_groups_public_read on public.pyq_question_groups;
create policy pyq_groups_public_read on public.pyq_question_groups for select using (true);

drop policy if exists pyq_group_members_public_read on public.pyq_question_group_members;
create policy pyq_group_members_public_read on public.pyq_question_group_members for select using (true);

drop policy if exists pyq_analysis_cache_public_read on public.pyq_course_analysis_cache;
create policy pyq_analysis_cache_public_read on public.pyq_course_analysis_cache for select using (true);
