-- Server-owned attendance storage. The Android client never receives direct Supabase access.
create table if not exists public.attendance_students (
  id uuid primary key default gen_random_uuid(),
  installation_hash text not null unique check (char_length(installation_hash) = 64),
  access_token_hash text not null unique check (char_length(access_token_hash) = 64),
  profile_fingerprint text not null check (char_length(profile_fingerprint) between 16 and 128),
  branch text not null default '' check (char_length(branch) <= 80),
  subsection text not null default '' check (char_length(subsection) <= 40),
  timetable_group text not null default '' check (char_length(timetable_group) <= 40),
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.attendance_students(id) on delete cascade,
  attendance_date date not null,
  lecture_key text not null check (char_length(lecture_key) between 16 and 128),
  status text not null check (status in ('present', 'absent')),
  subject text not null default '' check (char_length(subject) <= 240),
  teacher text not null default '' check (char_length(teacher) <= 240),
  venue text not null default '' check (char_length(venue) <= 240),
  start_minutes integer not null check (start_minutes between 0 and 1439),
  end_minutes integer not null check (end_minutes between 1 and 1440 and end_minutes > start_minutes),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, attendance_date, lecture_key)
);

create index if not exists attendance_records_student_date_idx
  on public.attendance_records(student_id, attendance_date desc);
create index if not exists attendance_records_student_status_idx
  on public.attendance_records(student_id, status);

create or replace function public.set_attendance_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists attendance_records_set_updated_at on public.attendance_records;
create trigger attendance_records_set_updated_at
before update on public.attendance_records
for each row execute function public.set_attendance_updated_at();

alter table public.attendance_students enable row level security;
alter table public.attendance_records enable row level security;

-- All attendance reads/writes go through the Vercel API using its server-only service role.
revoke all on table public.attendance_students from public, anon, authenticated;
revoke all on table public.attendance_records from public, anon, authenticated;
revoke all on sequence public.attendance_records_id_seq from public, anon, authenticated;
revoke all on function public.set_attendance_updated_at() from public, anon, authenticated;
