-- Leaderboard profile metadata and self-report audit history.
-- All access remains server-side through the Supabase service role.
alter table public.attendance_students
  add column if not exists display_name text not null default '' check (char_length(display_name) <= 160),
  add column if not exists section text not null default '' check (char_length(section) <= 40);

create index if not exists attendance_students_scope_idx
  on public.attendance_students(subsection, section, branch);

create table if not exists public.attendance_record_events (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.attendance_students(id) on delete cascade,
  attendance_date date not null,
  lecture_key text not null check (char_length(lecture_key) between 16 and 128),
  previous_status text check (previous_status is null or previous_status in ('present', 'absent')),
  new_status text check (new_status is null or new_status in ('present', 'absent')),
  source text not null default 'self_reported' check (source = 'self_reported'),
  changed_at timestamptz not null default now()
);

create index if not exists attendance_record_events_student_time_idx
  on public.attendance_record_events(student_id, changed_at desc);

alter table public.attendance_record_events enable row level security;
revoke all on table public.attendance_record_events from public, anon, authenticated;
revoke all on sequence public.attendance_record_events_id_seq from public, anon, authenticated;
